spring.application.name=websocket-handler-microservice
logging.level.org.springframework.boot.autoconfigure=ERROR
spring.profiles.active=development
environment.name=dev
release.version=0.0.dev
spring.devtools.add-properties=false
spring.resources.cache.period=0
spring.resources.chain.cache=false