spring.application.name=websocket-handler-microservice
server.servlet.context-path=/ws-service
logging.level.org.springframework.boot.autoconfigure=INFO
spring.profiles.active=development
environment.name=dev
release.version=0.0.dev
spring.devtools.livereload.enabled=true

# Redis Configs
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.username=admin
spring.data.redis.password=password
spring.redis.timeout=10s
spring.redis.lettuce.pool.max-active=8

#CORS Settings
ws.cors.origins.allowed=https://traderjam.online

management.endpoints.web.exposure.include=mappings