spring.application.name=websocket-handler-microservice
logging.level.org.springframework.boot.autoconfigure=ERROR
spring.profiles.active=test
environment.name=dev
release.version=0.0.dev
spring.devtools.add-properties=false